### ISSUE TITLE
Missing stop.sh

### ISSUE THREAD

**Issue by loriszigliani** [pixilab/net-blocks#3]
When i need to update Blocks server on debian, i start update_script.sh. but on server is missing file stop.sh

**Comment by TheWizz** [comment]
I don't see a script with the name update_script.sh in the net-blocks project. Perhaps you have obtained update_script.sh from somewhere else, such as our full Linux server image? If so, you should be able to find the start.sh and stop.sh scripts there too. 

This is essentially what the start.sh script does in relation to Blocks

**systemctl --user _start_ blocks**

The stop.sh script does the same, but replace _start_ with _stop_.

Mike

**Comment by TheWizz** [comment]
To update Blocks on your server, you should be able to roughly follow this guide:

https://pixilab.se/docs/blocks/server/update_blocks

but replace the start.sh and stop.sh scripts (which don't exist there) with the command lines shown above.

Mike
